name: Deploy Selector

on:
    workflow_dispatch:
        inputs:
            target:
                description: "What to deploy"
                required: true
                type: choice
                options:
                    - app
                    - workers
                    - both

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main
              uses: actions/checkout@v4

            - name: Deploy App branch
              if: ${{ inputs.target == 'app' || inputs.target == 'both' }}
              run: |
                  git config user.name "github-actions"
                  git config user.email "actions@github.com"

                  git checkout -B application
                  git push origin application --force

            - name: Deploy Workers branch
              if: ${{ inputs.target == 'workers' || inputs.target == 'both' }}
              run: |
                  git config user.name "github-actions"
                  git config user.email "actions@github.com"

                  git checkout -B workers
                  git push origin workers --force
